version = 3.11.5
style = default
maxColumn = 120
align.tokens = ["|", "=>", "<-", "=", "\"\"\""]
runner.dialect = scala213Source3
rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.newSyntax.control = false
runner.dialectOverride.allowSignificantIndentation = false
runner.dialectOverride.allowAsForImportRename = false
runner.dialectOverride.allowStarWildcardImport = false
fileOverride {
  "glob:**/project/**" {
    runner.dialect = scala3
  }
  "glob:**/*.sbt" {
    runner.dialect = scala3
  }
}
