name: ci
on:
  push:
  pull_request:
  schedule:
  - cron: '0 1 * * *'
jobs:
  test:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 8
            os: ubuntu-latest
          - java: 8
            os: windows-latest
          - java: 25
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-java@v5
      with:
        java-version: ${{ matrix.java }}
        distribution: zulu
    - uses: actions/checkout@v6
    - uses: coursier/cache-action@v7
    - uses: sbt/setup-sbt@v1
    - if: matrix.os == 'ubuntu-latest'
      run: sbt -v "all scalafmtSbtCheck scalafmtCheckAll"
    - run:
        sbt -v
        -no-colors
        coursierBootstrap
        publishLocal
        test
    - if: ${{ matrix.java == '8' && matrix.os == 'ubuntu-latest' }}
      run:
        sbt -v
        -no-colors
        publishLocal
        scripted
        makeSite
  push_gh_pages:
    needs: test
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v5
      with:
        java-version: 8
        distribution: adopt
    - uses: actions/checkout@v6
      with:
        fetch-depth: 10
    - uses: coursier/cache-action@v7
    - uses: sbt/setup-sbt@v1
    - run: sbt makeSite
    - id: generate_token
      uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
      if: ${{ github.repository_owner == 'foundweekends' && github.ref == 'refs/heads/develop' && github.event_name == 'push' }}
      with:
        app-id: 89697
        private-key: ${{ secrets.FOUNDWEEKENDS_BOT_KEY }}
    - name: Push to gh-pages
      if: ${{ github.repository_owner == 'foundweekends' && github.ref == 'refs/heads/develop' && github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@9d877eea73427180ae43cf98e8914934fe157a1a # v4.7.6
      with:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        BRANCH: gh-pages
        FOLDER: target/site
        CLEAN: true
