name: ci
on:
  push:
  pull_request:
  schedule:
  - cron: '0 1 * * *'
jobs:
  test:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 8
            os: ubuntu-latest
          - java: 8
            os: windows-latest
          - java: 25
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-java@v5
      with:
        java-version: ${{ matrix.java }}
        distribution: zulu
    - uses: actions/checkout@v5
    - uses: coursier/cache-action@v6
    - uses: sbt/setup-sbt@v1
    - if: matrix.os == 'ubuntu-latest'
      run: sbt -v "all scalafmtSbtCheck scalafmtCheckAll"
    - run:
        sbt -v
        -no-colors
        coursierBootstrap
        publishLocal
        test
    - if: ${{ matrix.java == '8' && matrix.os == 'ubuntu-latest' }}
      run:
        sbt -v
        -no-colors
        publishLocal
        scripted
        makeSite
  push_gh_pages:
    needs: test
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v5
      with:
        java-version: 8
        distribution: adopt
    - uses: actions/checkout@v5
      with:
        fetch-depth: 10
    - uses: coursier/cache-action@v6
    - uses: sbt/setup-sbt@v1
    - run: sbt makeSite
    - id: generate_token
      uses: tibdex/github-app-token@v2
      if: ${{ github.repository_owner == 'foundweekends' && github.ref == 'refs/heads/develop' && github.event_name == 'push' }}
      with:
        app_id: 89697
        private_key: ${{ secrets.FOUNDWEEKENDS_BOT_KEY }}
    - name: Push to gh-pages
      if: ${{ github.repository_owner == 'foundweekends' && github.ref == 'refs/heads/develop' && github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8 # v4.7.3
      with:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        BRANCH: gh-pages
        FOLDER: target/site
        CLEAN: true
