name: ci
on:
  push:
  pull_request:
  schedule:
  - cron: '0 1 * * *'
jobs:
  test:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 8
            os: ubuntu-latest
            name: test_all
          - java: 8
            os: windows-latest
            name: scala_2_13 # TODO enable scripted test
          - java: 8
            os: ubuntu-latest
            name: scala_2_13
          - java: 11
            os: ubuntu-latest
            name: test_all
    runs-on: ${{ matrix.os }}
    steps:
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.${{ matrix.java }}"
    - uses: actions/checkout@v2.3.4
    - uses: coursier/cache-action@v5
    - shell: bash
      run: |
        case ${{ matrix.name }} in
          "test_all")
            sbt -v \
            -no-colors \
            publishLocal \
            scalafmtCheckAll \
            launcher/test \
            plugin/scripted \
            scaffold/scripted \
            lib/test \
            app/compile
            ;;
          "scala_2_13")
            sbt -v SetScala213 app/test lib/test
            ;;
          *)
            echo "unknown job"
            exit 1
        esac
  push_gh_pages:
    needs: test
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.8"
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 10
    - uses: coursier/cache-action@v5
    - uses: webfactory/ssh-agent@v0.5.0
      if: ${{ !github.event.repository.fork && github.ref == 'refs/heads/master' && github.event_name == 'push' }}
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY_1 }}
    - name: Push to gh-pages
      if: ${{ !github.event.repository.fork && github.ref == 'refs/heads/master' && github.event_name == 'push' }}
      run: |
        # https://github.com/sbt/sbt-ghpages/commit/cbedd8edb8
        export SBT_GHPAGES_COMMIT_MESSAGE="auto commit on CI https://github.com/foundweekends/giter8/commit/${{ github.sha }}"
        sbt -v pushSiteIfChanged
