name: ci
on:
  push:
  pull_request:
  schedule:
  - cron: '0 1 * * *'
jobs:
  test:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 8
            os: ubuntu-latest
          - java: 8
            os: windows-latest
          - java: 21
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-java@v5
      with:
        java-version: ${{ matrix.java }}
        distribution: adopt
    - uses: actions/checkout@v5
    - uses: coursier/cache-action@v6
    - uses: sbt/setup-sbt@v1
    - if: matrix.os == 'ubuntu-latest'
      run: sbt -v "all scalafmtSbtCheck scalafmtCheckAll"
    - run:
        sbt -v
        -no-colors
        publishLocal
        test
    - if: ${{ matrix.java == '8' && matrix.os == 'ubuntu-latest' }}
      run:
        sbt -v
        -no-colors
        publishLocal
        scripted
        makeSite
  push_gh_pages:
    needs: test
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v5
      with:
        java-version: 8
        distribution: adopt
    - uses: actions/checkout@v5
      with:
        fetch-depth: 10
    - uses: coursier/cache-action@v6
    - uses: sbt/setup-sbt@v1
    - uses: webfactory/ssh-agent@v0.9.1
      if: ${{ github.repository_owner == 'foundweekends' && github.ref == 'refs/heads/develop' && github.event_name == 'push' }}
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY_1 }}
    - name: Push to gh-pages
      if: ${{ github.repository_owner == 'foundweekends' && github.ref == 'refs/heads/develop' && github.event_name == 'push' }}
      run: |
        # https://github.com/sbt/sbt-ghpages/commit/cbedd8edb8
        export SBT_GHPAGES_COMMIT_MESSAGE="auto commit on CI https://github.com/foundweekends/giter8/commit/${{ github.sha }}"
        sbt -v pushSiteIfChanged
