name: scala-steward
on:
  push:
    branches: [ develop ]
  schedule:
  - cron: '0 14 * * *'
  workflow_dispatch:
jobs:
  scala-steward:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ github.repository_owner == 'foundweekends' }}
    steps:
    - uses: sbt/setup-sbt@v1
    - name: Generate token
      id: generate_token
      uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
      with:
        client-id: 89697
        private-key: ${{ secrets.FOUNDWEEKENDS_BOT_KEY }}
    - name: Launch Scala Steward
      uses: scala-steward-org/scala-steward-action@b186ab858ce163f9af7b016fac32cfb3f2c2f503 # v2.88.0
      with:
        github-token: ${{ steps.generate_token.outputs.token }}
        author-email: "74864734+foundweekends-bot[bot]@users.noreply.github.com"
        author-name: "foundweekends-bot[bot]"
