name: scala-steward
on:
  push:
    branches: [ develop ]
  schedule:
  - cron: '0 14 * * *'
  workflow_dispatch:
jobs:
  scala-steward:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ github.repository_owner == 'foundweekends' }}
    steps:
    - uses: sbt/setup-sbt@v1
    - name: Generate token
      id: generate_token
      uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
      with:
        app-id: 89697
        private-key: ${{ secrets.FOUNDWEEKENDS_BOT_KEY }}
    - name: Launch Scala Steward
      uses: scala-steward-org/scala-steward-action@2aa539542d5fa259e430f9f65f3e0b962f6df9cc # v2.85.0
      with:
        github-token: ${{ steps.generate_token.outputs.token }}
        author-email: "74864734+foundweekends-bot[bot]@users.noreply.github.com"
        author-name: "foundweekends-bot[bot]"
